// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSTYhXsxOi_XDpTMwiAhAow86tWePrK8',
    appId: '1:970909451650:android:366486b8ae55f7a9333b9b',
    messagingSenderId: '970909451650',
    projectId: 'auth-38344',
    storageBucket: 'auth-38344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwfMSAHUTA0d26_xzg2aVR7tyXWA67FnU',
    appId: '1:970909451650:ios:ba35293046ba9976333b9b',
    messagingSenderId: '970909451650',
    projectId: 'auth-38344',
    storageBucket: 'auth-38344.firebasestorage.app',
    androidClientId: '970909451650-1mihorat9cop6d1vut5j44ga5jbod2he.apps.googleusercontent.com',
    iosClientId: '970909451650-cpejngv5pet98bull5ju3kvdg05cdth6.apps.googleusercontent.com',
    iosBundleId: 'com.thedeveloper.gnextlogistics',
  );
}
