spring.datasource.url=jdbc:mysql://45.12.136.148:3306/gnext
spring.datasource.username=root
spring.datasource.password=Trivalll43345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
socket.port=8081
socket.host=0.0.0.0